-- Insert all the tag data
INSERT INTO
    tags (id, name, description, category)
VALUES
    (1, 'Angry', 'Angry reaction', 'emotion'),
    (2, 'Artsy', 'Artsy/creative', 'style'),
    (3, 'Better', 'Better than expected', 'quality'),
    (4, 'Big', 'Big/large scale', 'size'),
    (5, 'Boss', 'Boss level difficulty', 'difficulty'),
    (6, 'Bug', 'Bug or glitch', 'issue'),
    (
        7,
        'CantBeat',
        'Cannot beat this level',
        'difficulty'
    ),
    (
        8,
        'Confusing',
        'Confusing or unclear',
        'clarity'
    ),
    (9, 'Cool', 'Cool/awesome', 'positive'),
    (10, 'Cute', 'Cute/adorable', 'style'),
    (11, 'Danger', 'Dangerous/hazardous', 'theme'),
    (12, 'Easy', 'Easy difficulty', 'difficulty'),
    (13, 'Empty', 'Empty or sparse', 'content'),
    (14, 'Enemies', 'Has enemies', 'gameplay'),
    (15, 'Flying', 'Flying mechanics', 'gameplay'),
    (16, 'Gems', 'Gem collection', 'gameplay'),
    (17, 'GoodIdea', 'Good idea/concept', 'quality'),
    (18, 'Great', 'Great quality', 'quality'),
    (19, 'Heart', 'Heart/love', 'emotion'),
    (
        20,
        'HiScore',
        'High score potential',
        'achievement'
    ),
    (21, 'Jumping', 'Jumping mechanics', 'gameplay'),
    (22, 'Like', 'Like this', 'positive'),
    (23, 'Lol', 'Funny/humorous', 'emotion'),
    (24, 'Long', 'Long level', 'duration'),
    (25, 'Maze', 'Maze-like structure', 'gameplay'),
    (26, 'MindBlown', 'Mind-blowing', 'reaction'),
    (27, 'Nice', 'Nice/pleasant', 'positive'),
    (28, 'Ninjas', 'Ninja theme', 'theme'),
    (29, 'Pretty', 'Pretty/beautiful', 'style'),
    (30, 'Puzzle', 'Puzzle elements', 'gameplay'),
    (31, 'Racing', 'Racing game', 'genre'),
    (32, 'SciFi', 'Science fiction theme', 'theme'),
    (33, 'Silly', 'Silly/funny', 'style'),
    (34, 'Spooky', 'Spooky/scary', 'theme'),
    (35, 'Thumb', 'Thumbs up', 'positive'),
    (36, 'Traps', 'Has traps', 'gameplay'),
    (37, 'Troll', 'Trolling/humor', 'style'),
    (38, 'Weird', 'Weird/unusual', 'style'),
    (39, 'Western', 'Western theme', 'theme'),
    (
        40,
        'Winner',
        'Winner/achievement',
        'achievement'
    ),
    (41, 'Zapper', 'Zapper/shooting', 'gameplay'),
    (42, 'Action', 'Action-packed', 'genre'),
    (
        43,
        'CoolCode',
        'Cool code/programming',
        'technical'
    ),
    (44, 'Dance', 'Dance/music', 'theme'),
    (45, 'Drama', 'Dramatic content', 'theme'),
    (46, 'Family', 'Family-friendly', 'audience'),
    (47, 'Friends', 'Friends theme', 'theme'),
    (48, 'Mystery', 'Mystery elements', 'theme'),
    (49, 'Pets', 'Pet theme', 'theme'),
    (50, 'Photos', 'Photo-related', 'content'),
    (51, 'Sports', 'Sports theme', 'theme'),
    (52, 'Travel', 'Travel theme', 'theme'),
    (53, 'Machine', 'Machine/robot theme', 'theme'),
    (54, 'VoteYellow', 'Yellow vote', 'voting'),
    (55, 'VoteRed', 'Red vote', 'voting'),
    (56, 'VoteBlue', 'Blue vote', 'voting'),
    (57, 'Magic', 'Magic theme', 'theme'),
    (58, 'Explore', 'Exploration', 'gameplay'),
    (59, 'Escape', 'Escape mechanics', 'gameplay'),
    (60, 'Learn', 'Educational/learning', 'purpose');